"""Compare the data files generated by the ported ADVFLS (PASTA/80 typed
file format) record by record with the original OMSI/RSX data files.
usage: verify-data.py <original-dir> <generated-dir>

OMSI files: fixed-length records numbered from 1, packed into 512-byte
blocks without spanning block boundaries.
PASTA files: 4-byte header (record count, record size), then the records,
numbered from 0 (record 0 is a dummy in the ported files).
"""
import struct, sys, os

orig, gen = sys.argv[1], sys.argv[2]

def omsi(name, size):
    d = open(os.path.join(orig, name), 'rb').read()
    per = 512 // size
    recs = [None]                      # OMSI records start at 1
    for b in range(len(d) // 512):
        for i in range(per):
            o = b * 512 + i * size
            recs.append(d[o:o + size])
    return recs

def pasta(name):
    d = open(os.path.join(gen, name), 'rb').read()
    count, size = struct.unpack('<hh', d[:4])
    return [d[4 + i * size:4 + (i + 1) * size] for i in range(count)], size

def ints(rec):
    return list(struct.unpack('<%dh' % (len(rec) // 2), rec))

errors = 0
def check(label, a, b):
    global errors
    if a != b:
        errors += 1
        if errors <= 20: print('  MISMATCH %s: %r != %r' % (label, a, b))

# ADVTXT: OMSI LOC + ARRAY[1..72] OF CHAR, PASTA LOC + STRING[72]
o = omsi('advtxt.dta', 74)
p, size = pasta('advtxt.dta')
print('ADVTXT.DTA: %d generated records (size %d)' % (len(p) - 1, size))
for r in range(1, len(p)):
    oloc, = struct.unpack('<h', o[r][:2])
    otxt = o[r][2:].decode('latin1').rstrip(' \0')
    ploc, n = struct.unpack('<hB', p[r][:3])
    ptxt = p[r][3:3 + n].decode('latin1').rstrip(' ')
    check('text %d' % r, (oloc, otxt), (ploc, ptxt))

# KATAB: 26 + 2 integers per record in both formats
o = omsi('katab.dta', 56)
p, size = pasta('katab.dta')
print('KATAB.DTA : %d generated records (size %d)' % (len(p) - 1, size))
for r in range(1, len(p)):
    check('vocab %d' % r, ints(o[r]), ints(p[r]))

# ADVDAT and ADVENT: files of integer
for name in ('advdat.dta', 'advent.dta'):
    o = omsi(name, 2)
    p, size = pasta(name)
    print('%-10s: %d generated records (size %d)' % (name.upper(), len(p) - 1, size))
    for r in range(1, len(p)):
        check('%s %d' % (name, r), ints(o[r]), ints(p[r]))

print('OK, all records identical' if errors == 0 else '%d mismatches' % errors)
sys.exit(1 if errors else 0)
